### ISSUE TITLE
Alacarte 0.1.31

### ISSUE THREAD

**Issue by cerealcable** [hatchrbr/django-alacarte#9]
I installed alacarte recently and got 0.1.31 but noticed it wasn't a release on github nor was it marked as the latest version on pypi which confused me. Thought I'd at least mention it!

**Comment by mstrcnvs** [comment]
My apologies, deleted the 0.1.31 release, the latest one is 1.5.
Something really weird happened because in fact there's no 0.1.31 release for django-alacarte. I released another package with this version number these days and PyPI must have freaked out.
